.TH package-assembler 1 "Package Assembler"

.SH NAME
package-assembler - Make debian packages easily!

.SH SYNOPSIS
.B package-assembler
.RI [-h, --help] [-c, --create], [-n --new-version]
.br

.SH DESCRIPTION
This program creates Debian package files.

.SH OPTIONS
.IP \fB\-h,--help\fP
Display the help message
.IP \fB\-c,--create\fP
Create a new debian project
.IP \fB\-n,--new-version\fP
Add a new version to the changelog

.SH NOTES

.SH "SEE ALSO"

